### ISSUE TITLE
licensing clarification

### ISSUE THREAD

**Issue by zabbal** [ARCCN/runos#1]
COPYING file missing as well as corresponding headers in source files - it's unclear, under which license this code is published?

**Comment by drwatson32** [comment]
Any news on that?

**Comment by ashalimov** [comment]
It will be Apache v2.0. Next week I'll make the commit. Is it ok licence for you?

**Comment by drwatson32** [comment]
At least it will allow to fork.
So yes, that will be good.

**Comment by ashalimov** [comment]
Finally, moved to Apache
