### ISSUE TITLE
Maple удаляет повторно созданные правила

### ISSUE THREAD

**Issue by romanov6416** [ARCCN/runos#10]
Ситуация:
1) Были залиты правила для прохождения ssh трафика (в обе стороны).
2) После того, как idle_timeout истек для установленных правил делаем попытку снова инициализировать такое же ssh соединение.
3) в результате maple присылает удаление правила для только что созданного ssh соединения.

**Comment by dShvetsov** [comment]
Логика Maple вынуждает изменять приоритет у некоторых потоков. Поэтому контроллеру приходится очищать все правила, постовленные с помощью Maple и устанавливать их заново.
Вы можете фильтровать flowRemoved  по причине удаления.
