### ISSUE TITLE
idleTimeout error

### ISSUE THREAD

**Issue by Kristofer76** [ARCCN/runos#11]
User case:
Send packet from 10.0.0.6 (for example) to 10.0.0.3 (also for example) using netcat.
When packets comes on controller, there creates a rule for balancing it (redirecting). So, after send I have this rule in table (check using  ovs-ofctl).
Then wait time = idleTimeout. Check that the rule was erased (also by  ovs-ofctl).
Send  packet from 10.0.0.6  to 10.0.0.3  using netcat again.

Nothing happens. No PacketIn comes on controller.

**Comment by ashalimov** [comment]
Thanks, we will check soon how the controller works with idle_timeout.

**Comment by dShvetsov** [comment]
Could you please provide the code where you are installing balancing rules?

**Comment by Kristofer76** [comment]
https://gist.github.com/Kristofer76/f0edd4c44cda89f31c8d53e164b65b40

**Comment by dShvetsov** [comment]
You are installing rule by sending flowmod packets by hand. But there are applications, that also install a rules using Maple system.
This maple rules are placed in last flow table in switch. Thus packets never matching by its, while your rule is installed. But when your rule expires, packets handling by maple rule.
You can manipulate idle timeouts of maple rules. For this you need in your handler of packetIn write the following code:
`decision = decision.idle_timeout(std::chrono::seconds(Your_timeout));`.
And when your rule expires, maple rule also expire.
