### ISSUE TITLE
Не правильно запускаются или совсем не запускаются приложения.

### ISSUE THREAD

**Issue by ThatNoha** [ARCCN/runos#13]
Не запускаются некоторые приложения RUNOS, в частности LearningSwitch.cc.
Версия RUNOS 0.6.2, операционная система - Ubuntu 16.04 LTS.

При запуске RUNOS коммандой build/runos выводится следующий лог:
I0911 02:12:06.196362 31281 Loader.cc:154] Initializing...
I0911 02:12:06.196539 31281 Loader.cc:231]   init(controller)
I0911 02:12:06.197067 31281 Loader.cc:231]   init(rest-listener)
I0911 02:12:06.197302 31281 Loader.cc:231]   init(switch-manager)
I0911 02:12:06.197446 31281 Loader.cc:231]   init(link-discovery)
I0911 02:12:06.197546 31281 Loader.cc:231]   init(topology)
I0911 02:12:06.197695 31281 Loader.cc:231]   init(learning-switch)
I0911 02:12:06.197783 31281 Loader.cc:231]   init(host-manager)
I0911 02:12:06.197862 31281 Loader.cc:231]   init(webui)
I0911 02:12:06.197944 31281 Loader.cc:231]   init(static-flow-pusher)
I0911 02:12:06.198017 31281 Loader.cc:231]   init(switch-stats)
I0911 02:12:06.198112 31281 Loader.cc:231]   init(stp)
I0911 02:12:06.198213 31281 Loader.cc:231]   init(arp-handler)
I0911 02:12:06.198272 31281 Loader.cc:231]   init(flow-manager)
I0911 02:12:06.198336 31281 Loader.cc:231]   init(rest-multipart)
I0911 02:12:06.198446 31281 Loader.cc:231]   init(rest-flowmod)
I0911 02:12:06.198506 31281 Loader.cc:159] Starting...
I0911 02:12:06.198560 31281 Loader.cc:167]   startUp(host-manager)
I0911 02:12:06.198580 31281 Loader.cc:167]   startUp(webui)
I0911 02:12:06.198597 31281 Loader.cc:167]   startUp(rest-listener)
I0911 02:12:06.198673 31281 Loader.cc:167]   startUp(rest-flowmod)
I0911 02:12:06.198691 31281 Loader.cc:167]   startUp(static-flow-pusher)
I0911 02:12:06.198707 31281 Loader.cc:167]   startUp(topology)
I0911 02:12:06.198724 31281 Loader.cc:167]   startUp(switch-manager)
I0911 02:12:06.198740 31281 Loader.cc:167]   startUp(controller)
I0911 02:12:06.198760 31282 Controller.cc:839] Registered packet-in handlers: 
I0911 02:12:06.198786 31282 Controller.cc:841] 	arp-handler
I0911 02:12:06.198803 31282 Controller.cc:841] 	host-manager
I0911 02:12:06.198819 31282 Controller.cc:841] 	forwarding
I0911 02:12:06.198833 31282 Controller.cc:841] 	link-discovery
I0911 02:12:06.198848 31282 Controller.cc:843] .
Server running (0.0.0.0:6653)
I0911 02:12:06.199187 31281 Loader.cc:167]   startUp(learning-switch)
I0911 02:12:06.199219 31281 Loader.cc:167]   startUp(rest-multipart)
I0911 02:12:06.199239 31281 Loader.cc:167]   startUp(switch-stats)
I0911 02:12:06.199270 31281 Loader.cc:167]   startUp(flow-manager)
I0911 02:12:06.199291 31281 Loader.cc:167]   startUp(link-discovery)
I0911 02:12:06.199308 31281 Loader.cc:167]   startUp(stp)
I0911 02:12:06.199326 31281 Loader.cc:167]   startUp(arp-handler)
I0911 02:12:06.199342 31281 Loader.cc:180] Controller is up!
I0911 02:12:06.687422 31285 Controller.cc:658] Connection id=0 started
I0911 02:12:06.687994 31286 Controller.cc:663] Connection id=0 established

Но никакие сообщения от learningswtich не проходят. Пробовал писать в файл LearningSwitch.cc в void LearningSwitch::init комманды создания файла, но файл не создавался.

**Comment by dShvetsov** [comment]
Судя по предоставленным логам LearningSwitch запустился

```
> I0911 02:12:06.197695 31281 Loader.cc:231] init(learning-switch)
...
> I0911 02:12:06.198819 31282 Controller.cc:841] forwarding
...
> I0911 02:12:06.199187 31281 Loader.cc:167] startUp(learning-switch)
```

Вы можете показать код функции void LearningSwitch::init, и какие сообщения вы от нее ждете?

**Comment by ThatNoha** [comment]
Могу.
void LearningSwitch::init(Loader *loader, const Config &)
{
    std::cout << "BBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
    ofstream HTfile ;
    HTfile.open ("thefile.info") ;  
    HTfile << "CCCCCAAAAAAAAAAAAAAAAAWWWWWWWWWW" << endl ;
    HTfile.close() ; 
    Controller* ctrl = Controller::get(loader);
    auto topology = Topology::get(loader);
    auto db = std::make_shared<HostsDatabase>();
    ctrl->registerHandler("forwarding",
    [=](SwitchConnectionPtr connection) {
        const auto ofb_in_port = oxm::in_port();
        const auto ofb_eth_src = oxm::eth_src();
        const auto ofb_eth_dst = oxm::eth_dst();

        return [=](Packet& pkt, FlowPtr, Decision decision) {
            // Get required fields
            ethaddr dst_mac = pkt.load(ofb_eth_dst);

            db->learn(connection->dpid(),
                      pkt.load(ofb_in_port),
                      packet_cast<TraceablePacket>(pkt).watch(ofb_eth_src));

            auto target = db->query(dst_mac);

            // Forward
            if (target) {
                auto route = topology
                             ->computeRoute(connection->dpid(), target->dpid);

                if (route.size() > 0) {
                    DVLOG(10) << "Forwarding packet from "
                              << connection->dpid()
                              << ':' << uint32_t(pkt.load(ofb_in_port))
                              << " via port " << route[0].port
                              << " to " << ethaddr(pkt.load(ofb_eth_dst))
                              << " seen at " << target->dpid;
                    // unicast via core
                    return decision.unicast(route[0].port)
                                   .idle_timeout(std::chrono::seconds(60))
                                   .hard_timeout(std::chrono::minutes(30));
                } else if (connection->dpid() == target->dpid) {
                    DVLOG(10) << "Forwarding packet from "
                              << connection->dpid()
                              << ':' << uint32_t(pkt.load(ofb_in_port))
                              << " via port " << target->port;
                    // send through core border
                    return decision.unicast(target->port)
                                   .idle_timeout(std::chrono::seconds(60))
                                   .hard_timeout(std::chrono::minutes(30));
                } else {
                    LOG(WARNING)
                        << "Path from " << connection->dpid()
                        << " to " << target->dpid << " not found";
                    return decision.drop()
                                   .idle_timeout(std::chrono::seconds(30))
                                   .hard_timeout(std::chrono::seconds(60))
                                   .return_();
                }
            } else {
                if (not is_broadcast(dst_mac)) {
                    VLOG(5) << "Flooding for unknown address " << dst_mac;
                    return decision.broadcast()
                                   .idle_timeout(std::chrono::seconds::zero());
                }
                return decision.broadcast();
            }
        };
    });
}

Я ждал, вывода BBBBBBBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA и создания файла со словом CCCCCAAAAAAAAAAAAAAAAAWWWWWWWWWW.

**Comment by dShvetsov** [comment]
Попробуйте заменить `std::cout` на `LOG(WARNING)`.

А так же убедитесь, что вы запускаете исполяемый файл скомпилированный с вашими изменениями.

**Comment by agrml** [comment]
Вопрос решен в личном порядке. Никаких проблем с Runos нет.
