### ISSUE TITLE
README is suitable only for Ubuntu 17.

### ISSUE THREAD

**Issue by mlshf** [ARCCN/runos#15]
Build prerequisites consider that user has Ubuntu 17 installed.
However, on earlier OS versions like Ubuntu 16.04 only libevent 2.0.21 is available via apt-get utility and there's no information on which version of libevent is needed to compile RuNOS in its readme. 
In earlier versions there was a section in readme about which version of libevent is needed and how to install it.
It is still usable for latest RuNOS version and there is a stable libevent 2.1.8 already.
Future users would find information in readme about appropriate libevent version useful if it is updated.

**Comment by xenerizes** [comment]
Fixed in #27
