### ISSUE TITLE
Uninformative errors

### ISSUE THREAD

**Issue by ElenaTokareva** [ARCCN/runos#19]
Clion successfully compiles my app, but when I try to run it in console, I get en error which doesn't help to solve the problem. Screenshot is attached. 

![photo5266976983189923985](https://user-images.githubusercontent.com/14888081/33516356-9bf2e4f8-d782-11e7-8613-acfb75d55f39.jpg)

**Comment by ashalimov** [comment]
This is original C++ error - you tried to access to outside a vector. Use gdb to debug.
1. gdb ./build/runos
2. r <path_to_network_settings>

Please confirm if all is ok.

**Comment by ElenaTokareva** [comment]
I fixed my error, thanks.

**Comment by dShvetsov** [comment]
I think it is bad practice, when controller throws exception without telling why. We will wrap std::exception into runos::exception and add information about it.

**Comment by ashalimov** [comment]
Ok, good
