### ISSUE TITLE
Read vlan properly

### ISSUE THREAD

**Issue by dShvetsov** [ARCCN/runos#22]
PacketParser assign vlan wrong. It's needed to make work with vlan more acceptable. Also it's needed add opportunity to make sure if packet has vlan, and use of13::OFPVID_PRESENT bit in openflow rules.

**Comment by xenerizes** [comment]
Found `fix this` in `parse_l2`, is that "work with vlan" problem?

**Comment by dShvetsov** [comment]
Yes. This comment is related to this issue.
