### ISSUE TITLE
Turn on the tests

### ISSUE THREAD

**Issue by xenerizes** [ARCCN/runos#32]
Existing tests need to be turned on. We may compile and run them conditionally, if the end user or developer wants.

**Comment by xenerizes** [comment]
In progress. Finished tests are working well, so I will enable them in master. 

@dShvetsov Are maple tests required to be finished or there were too many changes since they were written?

**Comment by dShvetsov** [comment]
It will be cool if the maple tests will be turned on. But maple interfaces had change a lot. If you feel a strong yourself you can deal with it.
