### ISSUE TITLE
Building runos with make gives error

### ISSUE THREAD

**Issue by xfresh-aiRx** [ARCCN/runos#34]
After cmake build i wanted to build runos with *make* like described in the README,
but at the very end of the build i get an error.

#### make output 
Scanning dependencies of target heartbeatcore_autogen
(...)
[ 97%] Linking CXX executable runos
/nix/store/7bhi29ainf5rjrk7k7wyhndyskzyhsxh-binutils-2.31.1/bin/ld: /nix/store/ldrlkd4s2hqphnpl23isv7v0i0pmr8pg-fmt-3.0.1/lib/libfmt.a(format.cc.o): in function `fmt::SystemError::init(int, fmt::BasicCStringRef<char>, fmt::ArgList)':
(.text+0xa2a): undefined reference to `std::runtime_error::operator=(std::runtime_error&&)'
/nix/store/7bhi29ainf5rjrk7k7wyhndyskzyhsxh-binutils-2.31.1/bin/ld: /nix/store/chj6vxwck80zyba52af5vg2m479m7kd8-cpp-netlib-0.13-release/lib/libcppnetlib-server-parsers.a(server_request_parsers_impl.cpp.o): in function `boost::detail::invalid_utf32_code_point(unsigned int)':
(.text._ZN5boost6detail24invalid_utf32_code_pointEj[_ZN5boost6detail24invalid_utf32_code_pointEj]+0x30): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/runos-bin.dir/build.make:112: runos] Error 1
make[1]: *** [CMakeFiles/Makefile2:269: CMakeFiles/runos-bin.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by ARCCN** [comment]
fixed
