### ISSUE TITLE
Error when starting runos: zlib

### ISSUE THREAD

**Issue by xfresh-aiRx** [ARCCN/runos#35]
__OS: Ubuntu 18.04.3 LTS__

#### Starting runos with ./build/runos in nix-shell

I get following error when I try to start runos in nix-shell.

./build/runos: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory.

**Comment by ARCCN** [comment]
Please, delete build folder and rebuild RUNOS.

I can not repeat this error.

**Comment by xfresh-aiRx** [comment]
Deleted the whole repo and cloned it again. I get the same error. 
I've already installed the zlib dependency even though the nix-shell should come with one.

**Comment by estepanov-lvk** [comment]
Closed due to inactivity, feel free to open another ticket if the problem persists.
