### ISSUE TITLE
Error when running nix-shell command

### ISSUE THREAD

**Issue by serkann229** [ARCCN/runos#37]
I recloned several times repository but it did not help. The screenshot was attached. Can you guys help me ?

![Ekran Alıntısı](https://user-images.githubusercontent.com/52835154/91940324-efab0680-ecff-11ea-9e93-1544876f37b6.PNG)

**Comment by estepanov-lvk** [comment]
We updated nix configuration with last commit, this issue should be fixed.

**Comment by serkann229** [comment]
It worked! Thank you 👍
