### ISSUE TITLE
nginx problem

### ISSUE THREAD

**Issue by serkann229** [ARCCN/runos#38]
![image](https://user-images.githubusercontent.com/52835154/91991550-b1cbd380-ed3b-11ea-917c-061950081ac3.png)

And

![image](https://user-images.githubusercontent.com/52835154/91991660-d58f1980-ed3b-11ea-82bf-8760e7077981.png)

I could not solve the problem :( Can you guys help ?

**Comment by estepanov-lvk** [comment]
The output of commands "systemctl status nginx.service" and "journalctl -xe" (from the first screen) can provide some additional useful information.

But I can guess, that the problem could be in the line 15. Angle brackets are not needed there (so it should be "root /home/controller/runos/build/web;").

**Comment by estepanov-lvk** [comment]
Closed due to inactivity, feel free to open another ticket if the problem persists.
