### ISSUE TITLE
Can't connect to signal Flow::changeState

### ISSUE THREAD

**Issue by Gerold103** [ARCCN/runos#7]
Error:
QObject::connect: Cannot queue arguments of type 'State'
(Make sure 'State' is registered using qRegisterMetaType().)

Code:
`...`
`private slots:`
`	void`
`	slot_change_flow_state(Flow::State new_state, uint64_t cookie);`
`...`
`FlowPtr flow;`
`...`
`connect(flow.get(), &Flow::changeState, this, &Homework::slot_change_flow_state);`

**Comment by dShvetsov** [comment]
Hi,
Please tell us following information:
* What compiler are you using?
* Which version of Qt you have installed?

**Comment by Gerold103** [comment]
GCC compiler version:l
`gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

Qt version:
`Compiled with Qt Version 5.5.1`
