### ISSUE TITLE
idle_timeout rules resurrect after creation of new rule.

### ISSUE THREAD

**Issue by SVadim94** [ARCCN/runos#8]
Misuse cases:
Case I:
1. Creating idle_timeout rule (rule_1) with maple (e.g. return decision.idle_timeout(...)).
2. Waiting for timeout to be sure that rule was killed.
3. ovs_ofctl shows that we have rule_1 with cookie_1
4. Creating another idle_timeout rule (rule_2) in the same way.
5. ovs_ofctl shows that we have **rule_1 with cookie_1** and rule_2 with cookie_2. So the rule_1 resurrected with its original cookie.

Case II:
1. Creating idle_timeout rule (rule_1) with maple (e.g. return decision.idle_timeout(...)).
2. ovs_ofctl shows that we have rule_1 with cookie_1 and timeout_1
3. Creating another idle_timeout rule (rule_2) in the same way before timeout has left.
4. ovs_ofctl shows that we have rule_2 with cookie_2 and timeout_2 and rule_1 with cookie_1 and **timeout_2**. Since rule_2 has nullified rule_1's timeout.

**Comment by ashalimov** [comment]
Thanks for the issue. Could you please provide the code where you are installing such rules?
