### ISSUE TITLE
 typographical errors in documentation

### ISSUE THREAD

**Issue by Gerold103** [ARCCN/runos#9]
- [LeareningL2Switch](http://arccn.github.io/runos/doc/ru/ApplicationOverView.html#simplelearingswitch) -> LearningL2Switch
- [пакета протоколоа](http://arccn.github.io/runos/doc/ru/Components.html#api) -> пакета протоколов
- [функций обработчик в](http://arccn.github.io/runos/doc/ru/Components.html#api) -> функций обработчиков
- [базовые знанияе](http://arccn.github.io/runos/doc/ru/FirstStep.html#id2) -> базовые знания
- [которые вы создаете вам](http://arccn.github.io/runos/doc/ru/FirstStep.html#id2) -> которые вы создаете, вам 
- [соответсвии с тем в какой](http://arccn.github.io/runos/doc/ru/FirstStep.html#id2) -> соответсвии с тем, в какой
- [с остальными приложением](http://arccn.github.io/runos/doc/ru/FirstStep.html#_CPPv2N11Application4initEP6LoaderRK6Config) -> с остальными приложениями
- [обмене сообщениеми с](http://arccn.github.io/runos/doc/ru/WorkingWithController.html#_CPPv210Controller) -> обмене сообщениями с
- [соединеие с коммутаторм](http://arccn.github.io/runos/doc/ru/WorkingWithController.html#_CPPv2N13OFTransaction8responseE19SwitchConnectionPtrNSt10shared_ptrI10OFMsgUnionEE) -> соединение с коммутатором
- [стадии иниуиализации](http://arccn.github.io/runos/doc/ru/WorkingWithController.html#_CPPv2N10Controller12reserveTableEv) ->стадии инициализации
- [программисту, это программисту это прочитать](http://arccn.github.io/runos/doc/ru/WorkingWithController.html#id4) -> программисту, это прочитать
- [оброботчиков](http://arccn.github.io/runos/doc/ru/WorkingWithController.html#_CPPv2N10Controller15registerHandlerEPKc24PacketMissHandlerFactory) -> обработчиков
- [указываеть](http://arccn.github.io/runos/doc/ru/WorkingWithController.html#_CPPv2N10Controller15registerHandlerEPKc24PacketMissHandlerFactory) -> указывать
- [Bradcast](http://arccn.github.io/runos/doc/ru/WorkingWithController.html#id9) -> Broadcast

**Comment by SVadim94** [comment]
[регестрация](http://arccn.github.io/runos/doc/ru/FirstStep.html#id5) -> регистрация
